name: GitHub Actions Demo

on: [push]

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      # è¤‡æ•°ã‚³ãƒãƒ³ãƒ‰ã‚’å®Ÿè¡Œã™ã‚‹ã€‚
      - run: echo "Hello World!!ğŸŒ"

      - run: ls -ltra; pwd

      - name: "æŒ¨æ‹¶"
        run: echo "Nice to meet you!!"

      - name: "åå‰ã‚’è¨€ã†"
        run: echo "My Name is Taro!!"

      - name: "è¶£å‘³ã‚’è©±ã™"
        run: echo "I love programming!!"

      - name: "è‡ªå·±ç´¹ä»‹"
        run: |
          echo "Nice to meet you!!"
          echo "My Name is Taro!!"
          echo "I love programming!!"
