name: GitHub Actionsã®ã§ã‚‚ğŸª§ãã—ã¦JavaScriptã®å®Ÿè¡ŒğŸ’¨

on:
  # developãƒ–ãƒ©ãƒ³ãƒã«pushã•ã‚ŒãŸã‚‰å®Ÿè¡Œ
  push:
    branches:
      - develop

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      # è¤‡æ•°ã‚³ãƒãƒ³ãƒ‰ã‚’å®Ÿè¡Œã™ã‚‹ã€‚
      - run: echo "Hello World!!ğŸŒ"

      - run: ls -ltra; pwd

      - name: "æŒ¨æ‹¶"
        run: echo "Nice to meet you!!"

      - name: "åå‰ã‚’è¨€ã†"
        run: echo "My Name is Taro!!"

      - name: "è¶£å‘³ã‚’è©±ã™"
        run: echo "I love programming!!"

      - name: "è‡ªå·±ç´¹ä»‹"
        run: |
          echo "Nice to meet you!!"
          echo "My Name is Taro!!"
          echo "I love programming!!"

  # ã‚¸ãƒ§ãƒ–ã¯ä¸¦åˆ—ã§å®Ÿè¡Œã•ã‚Œã‚‹ã€‚
  echo_goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: "åˆ¥ã‚Œã®æŒ¨æ‹¶ã‚’ã™ã‚‹"
        run: echo "Good Bye!!"

  setup_and_run:
    runs-on: ubuntu-latest
    steps:
      # ğŸ‘‡ãƒªãƒã‚¸ãƒˆãƒªã®ã‚½ãƒ¼ã‚¹ã‚’æŒã£ã¦ãã‚‹ (https://github.com/actions/checkout)
      - name: ãƒªãƒã‚¸ãƒˆãƒªã®ãƒã‚§ãƒƒã‚¯ã‚¢ã‚¦ãƒˆ
        uses: actions/checkout@v4

      # ğŸ‘‡Node.jsã‚’ä½¿ãˆã‚‹ã‚ˆã†ã«ã™ã‚‹ (https://github.com/actions/setup-node)
      - name: Node.jsã®ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          #node-version: 'latest'

      - name: npmã‚¤ã‚½ã‚¹ãƒˆãƒ¼ãƒ«
        run: npm install

      - name: ã‚¹ã‚¯ãƒªãƒ—ãƒˆå®Ÿè¡ŒğŸ’«
        run: |
          node --version
          node index.js
